//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSAngularProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssetMaster
    {
        public int assetMasterId { get; set; }
        public Nullable<int> assetType { get; set; }
        public Nullable<int> make { get; set; }
        public Nullable<int> assetName { get; set; }
        public string model { get; set; }
        public string serialnumber { get; set; }
        public DateTime makeYear { get; set; }
        public string makeYearStr
        {
            get
            {
                return makeYear.ToString("yyyy-MM-dd");
            }
        }
        public DateTime purchaseDate { get; set; }
        public string purchaseDateStr
        {
            get
            {
                return purchaseDate.ToString("yyyy-MM-dd");
            }
        }
        public string warranty { get; set; }
        public Nullable<DateTime> warrantyFrom { get; set; }

        public Nullable<DateTime> warrantyTo { get; set; }
        

        public virtual tblAssetDefinition tblAssetDefinition { get; set; }
        public virtual tblAssetType tblAssetType { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
