//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSAngularProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchase
    {
        public int purchaseId { get; set; }
        public string purchaseOrderNo { get; set; }
        public Nullable<int> purchaseAssetName { get; set; }
        public Nullable<int> purchaseAssetType { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<int> purchaseVendorName { get; set; }
        public  DateTime purchaseDate { get; set; }
        public Nullable<DateTime> purchaseDelivDate { get; set; }
        public string purchaseStatus { get; set; }
        public string purchaseDateStr
        {
            get
            {
                return purchaseDate.ToString("yyyy-MM-dd");
            }
        }
        public DateTime vaildTo { get; set; }
        public string purchaseDelivDateStr
        {
            get
            {
                return purchaseDelivDate.ToString();
            }
        }
        public virtual tblAssetDefinition tblAssetDefinition { get; set; }
        public virtual tblAssetType tblAssetType { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
