//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMSAngularProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVendor()
        {
            this.tblAssetMasters = new HashSet<tblAssetMaster>();
            this.tblPurchases = new HashSet<tblPurchase>();
        }
    
        public int vendorId { get; set; }
        public string vendorName { get; set; }
        public string vendorType { get; set; }
        public Nullable<int> vendorAssetType { get; set; }
        public DateTime validFrom { get; set; }
        public string validFromStr
        {
            get
            {
                return validFrom.ToString("yyyy/MM/dd");
            }
        }
        public DateTime vaildTo { get; set; }
        public string validToStr
        {
            get
            {
                return vaildTo.ToString("yyyy/MM/dd");
            }
        }
        public string vendorAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssetMaster> tblAssetMasters { get; set; }
        public virtual tblAssetType tblAssetType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchase> tblPurchases { get; set; }
    }
}
